$(function(){
		
	$(".li_1").mouseenter(function(){
		$(".n_1").css("display","block");
		
		$(".n_1").mouseenter(function(){
			$(".n_1").css("display","block");
		})
		$(".n_1").mouseleave(function(){
			$(".n_1").css("display","none");
		})	
	})
	$(".li_1").mouseleave(function(){
		$(".n_1").css("display","none");
	})
	
	$(".li_2").mouseenter(function(){
		$(".n_2").css("display","block");
		$(".n_2").mouseenter(function(){
			$(".n_2").css("display","block");
		})
		$(".n_2").mouseleave(function(){
			$(".n_2").css("display","none");
		})	
	})
	$(".li_2").mouseleave(function(){
		$(".n_2").css("display","none");
	})
	$(".li_3").mouseenter(function(){
		$(".n_3").css("display","block");
		$(".n_3").mouseenter(function(){
			$(".n_3").css("display","block");
		})
		$(".n_3").mouseleave(function(){
			$(".n_3").css("display","none");
		})	
	})
	$(".li_3").mouseleave(function(){
		$(".n_3").css("display","none");
	})
	$(".li_4").mouseenter(function(){
		$(".n_4").css("display","block");
		$(".n_4").mouseenter(function(){
			$(".n_4").css("display","block");
		})
		$(".n_4").mouseleave(function(){
			$(".n_4").css("display","none");
		})	
	})
	$(".li_4").mouseleave(function(){
		$(".n_4").css("display","none");
	})
	$(".li_5").mouseenter(function(){
		$(".n_5").css("display","block");
		$(".n_5").mouseenter(function(){
			$(".n_5").css("display","block");
		})
		$(".n_5").mouseleave(function(){
			$(".n_5").css("display","none");
		})	
	})
	$(".li_5").mouseleave(function(){
		$(".n_5").css("display","none");
	})
	$(".li_6").mouseenter(function(){
		$(".n_6").css("display","block");
		$(".n_6").mouseenter(function(){
			$(".n_6").css("display","block");
		})
		$(".n_6").mouseleave(function(){
			$(".n_6").css("display","none");
		})	
	})
	$(".li_6").mouseleave(function(){
		$(".n_6").css("display","none");
	})
	$(".li_7").mouseenter(function(){
		$(".n_7").css("display","block");
		$(".n_7").mouseenter(function(){
			$(".n_7").css("display","block");
		})
		$(".n_7").mouseleave(function(){
			$(".n_7").css("display","none");
		})	
	})
	$(".li_7").mouseleave(function(){
		$(".n_7").css("display","none");
	})
	$(".li_8").mouseenter(function(){
		$(".n_8").css("display","block");
		$(".n_8").mouseenter(function(){
			$(".n_8").css("display","block");
		})
		$(".n_8").mouseleave(function(){
			$(".n_8").css("display","none");
		})	
	})
	$(".li_8").mouseleave(function(){
		$(".n_8").css("display","none");
	})
	$(".li_9").mouseenter(function(){
		$(".n_9").css("display","block");
		$(".n_9").mouseenter(function(){
			$(".n_9").css("display","block");
		})
		$(".n_9").mouseleave(function(){
			$(".n_9").css("display","none");
		})	
	})
	$(".li_9").mouseleave(function(){
		$(".n_9").css("display","none");
	})
	$(".li_10").mouseenter(function(){
		$(".n_10").css("display","block");
		$(".n_10").mouseenter(function(){
			$(".n_10").css("display","block");
		})
		$(".n_10").mouseleave(function(){
			$(".n_10").css("display","none");
		})	
	})
	$(".li_10").mouseleave(function(){
		$(".n_10").css("display","none");
	})
	$(".li_11").mouseenter(function(){
		$(".n_11").css("display","block");
		$(".n_11").mouseenter(function(){
			$(".n_11").css("display","block");
		})
		$(".n_11").mouseleave(function(){
			$(".n_11").css("display","none");
		})	
	})
	$(".li_11").mouseleave(function(){
		$(".n_11").css("display","none");
	})
	$(".li_12").mouseenter(function(){
		$(".n_12").css("display","block");
		$(".n_12").mouseenter(function(){
			$(".n_12").css("display","block");
		})
		$(".n_12").mouseleave(function(){
			$(".n_12").css("display","none");
		})	
	})
	$(".li_12").mouseleave(function(){
		$(".n_12").css("display","none");
	})
	$(".li_13").mouseenter(function(){
		$(".n_13").css("display","block");
		$(".n_13").mouseenter(function(){
			$(".n_13").css("display","block");
		})
		$(".n_13").mouseleave(function(){
			$(".n_13").css("display","none");
		})	
	})
	$(".li_13").mouseleave(function(){
		$(".n_13").css("display","none");
	})
	$(".li_14").mouseenter(function(){
		$(".n_14").css("display","block");
		$(".n_14").mouseenter(function(){
			$(".n_14").css("display","block");
		})
		$(".n_14").mouseleave(function(){
			$(".n_14").css("display","none");
		})	
	})
	$(".li_14").mouseleave(function(){
		$(".n_14").css("display","none");
	})
	$(".li_15").mouseenter(function(){
		$(".n_15").css("display","block");
		$(".n_15").mouseenter(function(){
			$(".n_15").css("display","block");
		})
		$(".n_15").mouseleave(function(){
			$(".n_15").css("display","none");
		})	
	})
	$(".li_15").mouseleave(function(){
		$(".n_15").css("display","none");
	})
})
